# Generated by Django 6.0.3 on 2026-03-07 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_team_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='timezone',
            field=models.CharField(choices=[('UTC', 'UTC'), ('America/New_York', 'Eastern Time'), ('America/Chicago', 'Central Time'), ('America/Denver', 'Mountain Time'), ('America/Los_Angeles', 'Pacific Time'), ('Europe/London', 'London'), ('Europe/Paris', 'Paris'), ('Asia/Tokyo', 'Tokyo'), ('Australia/Sydney', 'Sydney')], default='UTC', max_length=50),
        ),
    ]
