# Generated by Django 6.0.3 on 2026-03-09 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_alter_userprofile_timezone'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatistikJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('inventory_file', models.FileField(upload_to='analytics/inventory/%Y/%m/')),
                ('wayke_file', models.FileField(upload_to='analytics/wayke/%Y/%m/')),
                ('citk_file', models.FileField(upload_to='analytics/citk/%Y/%m/')),
                ('notes_file', models.FileField(blank=True, null=True, upload_to='analytics/notes/%Y/%m/')),
                ('inventory_sheet', models.CharField(default='toyota lager', max_length=100)),
                ('citk_sheet', models.CharField(default='Sheet1', max_length=100)),
                ('photo_min_urls', models.IntegerField(default=1)),
                ('kpis', models.JSONField(blank=True, null=True)),
                ('station_stats', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.userprofile')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistik_jobs', to='core.organization')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('daily', 'Daily Report'), ('weekly', 'Weekly Report'), ('custom', 'Custom Report')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('excel_file', models.FileField(blank=True, null=True, upload_to='analytics/exports/%Y/%m/')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='analytics/exports/%Y/%m/')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_reports', to='core.organization')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='services_analytics.statistikjob')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='VehicleRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=200)),
                ('status', models.IntegerField()),
                ('current_station', models.CharField(max_length=100)),
                ('days_in_stock', models.IntegerField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('is_photographed', models.BooleanField(default=False)),
                ('photo_count', models.IntegerField(default=0)),
                ('needs_photos', models.BooleanField(default=False)),
                ('missing_citk', models.BooleanField(default=False)),
                ('is_sold', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_records', to='services_analytics.statistikjob')),
            ],
            options={
                'indexes': [models.Index(fields=['job', 'registration'], name='services_an_job_id_b71eed_idx'), models.Index(fields=['job', 'current_station'], name='services_an_job_id_3525bf_idx')],
            },
        ),
    ]
