# Generated by Django 6.0.3 on 2026-03-22 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_analytics', '0002_vehiclerecord_vehiclevaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistikjob',
            name='job_type',
            field=models.CharField(choices=[('full', 'Full'), ('lite', 'Lite')], default='full', max_length=10),
        ),
        migrations.AddField(
            model_name='vehiclerecord',
            name='extra_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='statistikjob',
            name='inventory_file',
            field=models.FileField(blank=True, null=True, upload_to='analytics/inventory/%Y/%m/'),
        ),
    ]
