# Generated by Django 6.0.3 on 2026-03-23 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_userprofile_timezone"),
        ("services_analytics", "0003_lite_job_support"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalyticsTool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(max_length=120)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("icon", models.CharField(default="fas fa-tools", max_length=100)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("internal_url", "Internal URL"),
                            ("named_view", "Named View"),
                        ],
                        default="named_view",
                        max_length=20,
                    ),
                ),
                ("target_path", models.CharField(blank=True, max_length=255)),
                ("target_view_name", models.CharField(blank=True, max_length=255)),
                ("open_in_new_tab", models.BooleanField(default=False)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.userprofile",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics_tools",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "name"],
                "indexes": [
                    models.Index(
                        fields=["organization", "is_active"],
                        name="services_an_organiz_e58ddb_idx",
                    ),
                    models.Index(
                        fields=["organization", "action_type"],
                        name="services_an_organiz_8beee4_idx",
                    ),
                ],
                "unique_together": {("organization", "slug")},
            },
        ),
    ]
