# Generated by Django 6.0.4 on 2026-05-03 17:22

from django.db import migrations, models

def set_empty_emails_to_null(apps, schema_editor):
    CustomUser = apps.get_model('accounts', 'CustomUser')
    # Update all users where email is an empty string to None
    CustomUser.objects.filter(email='').update(email=None)

def reverse_set_empty_emails_to_null(apps, schema_editor):
    # This reverse operation is generally not needed for this specific cleanup
    # as converting None back to '' might reintroduce the unique constraint issue.
    # For development, leaving it as a no-op is usually fine.
    pass

class Migration(migrations.Migration):

    dependencies = [
        # IMPORTANT: Replace '00YY_auto_YYYYMMDD_HHMM' with the actual name of the previous migration file
        ('accounts', '0003_alter_customuser_email'),
    ]

    operations = [
        migrations.RunPython(set_empty_emails_to_null, reverse_set_empty_emails_to_null),
    ]


