# Generated by Django 6.0.4 on 2026-05-06 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_planning', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='project',
            new_name='job_plannin_organiz_576e84_idx',
            old_name='job_plannin_organiza_123456_idx',
        ),
        migrations.RenameIndex(
            model_name='project',
            new_name='job_plannin_organiz_11d316_idx',
            old_name='job_plannin_organiza_234567_idx',
        ),
        migrations.RenameIndex(
            model_name='project',
            new_name='job_plannin_organiz_c920fc_idx',
            old_name='job_plannin_organiza_345678_idx',
        ),
        migrations.RenameIndex(
            model_name='task',
            new_name='job_plannin_project_ba75f9_idx',
            old_name='job_plannin_project_456789_idx',
        ),
        migrations.RenameIndex(
            model_name='task',
            new_name='job_plannin_project_3f03dd_idx',
            old_name='job_plannin_project_567890_idx',
        ),
        migrations.RenameIndex(
            model_name='task',
            new_name='job_plannin_project_d0b7e2_idx',
            old_name='job_plannin_project_678901_idx',
        ),
    ]
