# Generated by GitHub Copilot on 2026-03-14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_userprofile_timezone"),
        ("services_dashboard", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DashboardPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("show_read_receipts", models.BooleanField(default=True)),
                ("desktop_notifications", models.BooleanField(default=True)),
                ("auto_mark_threads_read", models.BooleanField(default=True)),
                ("email_alerts", models.BooleanField(default=True)),
                (
                    "digest_frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("never", "Never"),
                        ],
                        default="weekly",
                        max_length=20,
                    ),
                ),
                ("message_retention_days", models.PositiveIntegerField(default=90)),
                (
                    "default_visibility",
                    models.CharField(
                        choices=[
                            ("participants", "Participants only"),
                            ("organization", "Organization-wide (group only)"),
                        ],
                        default="participants",
                        max_length=20,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user_profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dashboard_preferences",
                        to="core.userprofile",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="dashboardpreference",
            index=models.Index(
                fields=["digest_frequency"],
                name="services_da_digest__1ecda0_idx",
            ),
        ),
    ]