# Generated by Django 6.0.3 on 2026-03-29 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services_dashboard', '0002_dashboardpreference'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='dashboardpreference',
            new_name='services_da_digest__91428d_idx',
            old_name='services_da_digest__1ecda0_idx',
        ),
    ]
