# Generated by Django 6.0.3 on 2026-03-29 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_userprofile_timezone"),
        ("customer_support", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KBCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(max_length=120)),
                ("description", models.TextField(blank=True)),
                (
                    "icon",
                    models.CharField(blank=True, default="fa-book", max_length=50),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kb_categories",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "KB Category",
                "verbose_name_plural": "KB Categories",
                "ordering": ["sort_order", "name"],
                "unique_together": {("organization", "slug")},
            },
        ),
        migrations.CreateModel(
            name="KBArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255)),
                ("content", models.TextField()),
                (
                    "excerpt",
                    models.CharField(
                        blank=True,
                        help_text="Short summary shown in listings",
                        max_length=300,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=True,
                        help_text="Visible to customers; when False only staff can see it",
                    ),
                ),
                ("view_count", models.PositiveIntegerField(default=0)),
                ("helpful_count", models.PositiveIntegerField(default=0)),
                ("not_helpful_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "authored_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="kb_articles_authored",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kb_articles",
                        to="core.organization",
                    ),
                ),
                (
                    "related_tickets",
                    models.ManyToManyField(
                        blank=True,
                        related_name="kb_articles",
                        to="customer_support.supportticket",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="articles",
                        to="customer_support.kbcategory",
                    ),
                ),
            ],
            options={
                "ordering": ["-published_at", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["organization", "status", "is_public"],
                        name="customer_su_organiz_de585c_idx",
                    ),
                    models.Index(
                        fields=["organization", "category"],
                        name="customer_su_organiz_6bd52b_idx",
                    ),
                    models.Index(fields=["slug"], name="customer_su_slug_06d0da_idx"),
                ],
                "unique_together": {("organization", "slug")},
            },
        ),
    ]
