# Generated by Django 6.0.3 on 2026-03-28 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventorylocation",
            name="view_settings",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
